version: '3.8'

services:
  pama-smr:
    container_name: pama-smr
    build:
      context: .
      dockerfile: 1.PAMA.Razor.Views/Dockerfile
    ports:
      - "8080:80"
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.aws:/root/.aws:ro 
    restart: always

  pama-api:
    container_name: pama-api
    build:
      context: .
      dockerfile: 2.Web.API.Controllers/Dockerfile
    ports:
      - "8082:80"
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.aws:/root/.aws:ro 
    restart: always

  pama-scheduler:
    container_name: pama-scheduler
    build:
      context: .
      dockerfile: 8.PAMA.Scheduler/Dockerfile
    ports:
      - "8084:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.aws:/root/.aws:ro 
    restart: always