version: '3.8'

services:
  pama-smr:
    container_name: pama-smr
    build:
      context: .
      dockerfile: 1.PAMA.Razor.Views/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ~/.aws:/root/.aws:ro 
    restart: always

  pama-api:
    container_name: pama-api
    build:
      context: .
      dockerfile: 2.Web.API.Controllers/Dockerfile
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ~/.aws:/root/.aws:ro 
    restart: always
